[project]
name = "ok-ap"
version = "0.1.0"
description = "A ready-to-use template for building game automation tools on ok-script"
requires-python = ">=3.12,<3.13"
dependencies = [
    "ok-script==2.0.6",
    "PySide6-Essentials==6.11.1",
    "PySide6-Fluent-Widgets==1.10.5",
    "PySideSix-Frameless-Window==0.7.3",
    "onnxocr-ppocrv5==0.0.14",
    "openvino==2026.0.0",
    "opencv-python==4.12.0.88",
    "numpy>=2.0.0",
    "Pillow>=10.0.0",
    "json5==0.15.0",
    "pyautogui==0.9.54",
    "pynput==1.8.2",
]

[dependency-groups]
dev = [
    "polib",
    "pypinyin>=0.55,<1",
    "PyYAML>=6.0,<7",
    "ruff>=0.16,<1",
]

[tool.uv]
package = false
override-dependencies = [
    "pywin32==311; sys_platform == 'win32'",
] # Only Windows can install pywin32

[tool.ruff]
line-length = 120
target-version = "py312"
extend-exclude = ["ok_templates"]

[tool.ruff.lint]
allowed-confusables = ["，", "。", "；", "：", "（", "）", "、"]
select = ["E", "W", "F", "I", "C4", "B", "UP", "SIM", "RUF"]
ignore = [
    "E501",
    "D",
    "S101",
    "BLE001",
    "N",
    "C901",
    "RUF001",
    "RUF002",
    "PT",
    "PLR2004",
]

[tool.ruff.format]
quote-style = "double"
exclude = ["ok_templates"]